#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';

use App\Command\SolveCommand;
use Symfony\Component\Console\Application;

$application = new Application();

$application->add(new SolveCommand());

$application->run();